//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarDB_SQl_Lib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentCarDatabaseEntities1 : DbContext
    {
        public RentCarDatabaseEntities1()
            : base("name=RentCarDatabaseEntities1")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RentCarBranch> RentCarBranches { get; set; }
        public virtual DbSet<RentCarContact> RentCarContacts { get; set; }
        public virtual DbSet<RentCarUserDB> RentCarUserDBs { get; set; }
        public virtual DbSet<RentCarNewVehiclesDB> RentCarNewVehiclesDBs { get; set; }
        public virtual DbSet<RentCarRentedCar> RentCarRentedCars { get; set; }
        public virtual DbSet<RentCarUsersRentHistory> RentCarUsersRentHistories { get; set; }
        public virtual DbSet<RentCarServerErrorsLog> RentCarServerErrorsLogs { get; set; }
    }
}
