//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarDB_SQl_Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentCarUserDB
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public string IsAdmin { get; set; }
    }
}
